project:
  type: website
  
  
website:
  back-to-top-navigation: true
  sidebar: 
    search: true
    logo: images/logos_ine.svg
    logo-href: https://ine.gov.ar/
    contents: 
      - index.qmd
      - unidad_1.qmd
      - unidad_2.qmd
      - unidad_3.qmd
      
      
  body-header: |
    <center> Este material es parte del curso interno de Introducción a la Revisión Sistemática con Meta-análisis </br>
    © 2025 Instituto Nacional de Epidemiología "Dr. Juan H. Jara" (ANLIS) - 
    <a href="http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1"> CC BY-NC 4.0 </a>
    ![](images/cc01.svg){width="3%"}
    ![](images/cc02.svg){width="3%"}
    ![](images/cc03.svg){width="3%"} 
    </br>
    </br>
    </center>

format:
  html:
    theme: 
      light: default
      dark: cyborg
    include-in-header:
      text: |
        <style type="text/css">
        .quarto-reader-toggle .bi::before, .quarto-color-scheme-toggle .bi::before {
          display: inline-block;
          height: 40px;
          width: 40px;
          background-size: 25px 25px;
          background-position: center;
          background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgba(189, 195, 199, 1)" class="bi bi-moon-stars-fill" viewBox="0 0 16 16"> <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278"/> <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.73 1.73 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.73 1.73 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.73 1.73 0 0 0 1.097-1.097zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/> </svg>') !important;
        }
        </style>
    
    lang: es
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "Contenidos"
    search: true
    self_contained: true
  
other-links:
  - text: "Plataforma Educativa ANLIS"
    icon: tag-fill
    href: http://capacitacion.anlis.gob.ar/
  - text: "Github"
    icon: github
    href: https://github.com/datos-ine

editor: visual